name: Deploy Firebase Backend to Dev

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install Dependencies (Clean Install)
        run: npm ci
        working-directory: functions

      - name: ESLint fix
        run: npx eslint --fix .
        working-directory: functions

      - name: Lint Firebase Functions
        run: npx eslint .
        working-directory: functions

      - name: Set up Firebase authentication
        run: |
          printf '%s' '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > ${{ github.workspace }}/firebase-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=${{ github.workspace }}/firebase-key.json" >> $GITHUB_ENV

      - name: Deploy Firebase Functions
        run: firebase deploy --only functions
